baseURL = "http://example.org/"
languageCode = "en-us"
title = "Crossways Community Creche - Documents"
theme = "kube"
[Params]
  RSSLink = "/index.xml"
  author = "newpixcom" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "myemail@myaddress.xxx"

[[menu.main]]
    name = "Policies"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -80
    url = "/blog/"
